### ISSUE TITLE
audio resampling

### ISSUE THREAD

**Issue by cloudybyte** [codetheweb/aoede#1]
is there any reason for resampling the audio [here](https://github.com/codetheweb/aoede/blob/d25c8488cae442a890094308d87a4c0aa3ec099f/src/lib/player.rs#L85)? afaik it just causes cpu utilization... In fact why are we touching the audio data at all?

**Comment by cloudybyte** [comment]
ok if we don't reencode the audio sounds high pitched and speeded up.

**Comment by codetheweb** [comment]
In theory we should be able to add `passthrough: true` to the `PlayerConfig` init struct and pass unmodified OGG / Opus to Songbird (Discord voice library). I was never able to get it to work without having the issue you mention above, but happy to accept a PR if you figure it out. Impact in terms of CPU usage / audio quality seems to be minimal.

**Comment by cloudybyte** [comment]
i guess the audio speeds up cuz spotify plays back at 44.1khz and discord plays at 48khz. if we don't resample the audio it gets accellerated because discord consumes the data faster than its intended by spotify to be played back. I don't think there is any way around this but maybe its possible to pass a sampling frequency through to songbird...

**Comment by cloudybyte** [comment]
Nope, probably not possible, [the sampling rate is a constant](https://docs.rs/songbird/0.2.0/src/songbird/constants.rs.html#15). It would probably involve major refactoring on songbirds side or just processing it inside of songbird.
