### ISSUE TITLE
Getting Client Ended Error

### ISSUE THREAD

**Issue by shubhankartrivedi** [codetheweb/aoede#14]
I am getting the Error:

`Client ended: Http(UnsuccessfulRequest(ErrorResponse { status_code: 401, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v9/users/@me", query: None, fragment: None }, error: DiscordJsonError { code: 0, message: "401: Unauthorized", errors: [] } }))`

OS: Windows 11 
Yes I did got email from Spotify for Login .

**Comment by codetheweb** [comment]
Looks like it's having trouble connecting to Discord. Double check the bot token is correct?

**Comment by shubhankartrivedi** [comment]
> Looks like it's having trouble connecting to Discord. Double check the bot token is correct?

Yeah I have tried doing with fresh token also, same error. 
But tomorrow I'll try again

**Comment by Azumi0** [comment]
I faced the same issue, but I found a solution to it. You need to provide bot token, not user token, with user token bot won't work

**Comment by shubhankartrivedi** [comment]
> I faced the same issue, but I found a solution to it. You need to provide bot token, not user token, with user token bot won't work

I mean like it's obvious that we give bot token , who will give user token its dumb

**Comment by codetheweb** [comment]
Yep, happy to accept a PR with an update for that :)

**Comment by cloudybyte** [comment]
#19
