### ISSUE TITLE
improve docker builds

### ISSUE THREAD

**Issue by cloudybyte** [codetheweb/aoede#26]
We could think of publishing properly patched builds, so that people could use semantic versioning...
### Example:
Version 1.4.2 just got released and now the docker image is being built.
It should be tagged with: `latest`, `v1`, `v1.4` and `v1.4.2`.
This could include adding additional tags for different variants of the build after the last versioning digit (e.g. `v1.4.2-alpine`).
<br><br>
And I'd change the runtime image to `scratch` if thats possible, though I'm not fully sure if that'll work

**Comment by codetheweb** [comment]
Yep, I agree. I have similar versioning to what you described set up for [Muse](https://github.com/codetheweb/muse) and it works really well.

I'd also like to move to the self-hosted ARM runners I have rather than cross-compiling on x86 so workflows don't take hours to run.

**Comment by codetheweb** [comment]
This is now resolved.

Happy to accept a PR if you manage to change the final base image to `scratch`, but I think I ran into some issues with static linking last time I tried.
