### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by cloudybyte** [codetheweb/aoede#27]
Maybe we should think about collecting errors and crashes via sentry.

Don't know if that'd be too privacy invading/scary for users, some feedback would be great (@nodgear, @codetheweb)?
Not sure if opt in or opt out would be the way to go tho...

**Comment by nodgear** [comment]
Considering the license and the nature of discord bot it should be opt in.
Discord bots with `connect` permission are able to record stuff, making any type of telemetry opt-in should avoid criticism.

Out of scope, but also a good input: 
a node/deno binding for librespot would be a good project, allowing more people to make bots like Aoede.

**Comment by nodgear** [comment]
The thing is, not everyone has the technical ability to read the source code and determine what is being done with the data, but most of them can notice a discord bot sending information to another server.
Discord was criticized by those same people without knowing about sentry and log collection.

I understand that being opt-in prevents some of the diagnosis from ever seeing the light of day.

**Comment by cloudybyte** [comment]
While I understand your concern, I doubt, that there are people out there, who can detect a binary sending information to outside servers and not having a basic skills in reading code. 

What do you think of a mandatory config option `send_error_logs`, which has to be set in order for the bot to run?
(That would obviously include extending the README to explain exactly what we're collecting)

**Comment by codetheweb** [comment]
I will not collect any type of telemetry. 

This is FOSS, and personally I feel like telemetry goes against the ideals of that. Further, I (and anyone else working on this project) are under no obligations to fix bugs as fast as possible. Responding to issues as they come up works fine.
