### ISSUE TITLE
Unauthed on discord

### ISSUE THREAD

**Issue by MasterModz1243** [codetheweb/aoede#35]
I saw this issue was posted a little while ago but you just marked it as using a client token and i want to make it clear that **i am not using a client token** 

`Client ended: Http(UnsuccessfulRequest(ErrorResponse { status_code: 401, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v10/users/@me", query: None, fragment: None }, error: DiscordJsonError { code: 0, message: "401: Unauthorized", errors: [] } }))`

**Comment by codetheweb** [comment]
Can you clarify what issue you're referencing? The error message seems pretty clear that it's a bad token.

**Comment by codetheweb** [comment]
Edit: I assume this is for https://github.com/codetheweb/aoede/issues/34, closing this in favor of continuing the conversation there.
