### ISSUE TITLE
Joins voice channel but doesn't broadcast audio

### ISSUE THREAD

**Issue by myde2001** [codetheweb/aoede#36]
The bot appears in the Spotify Connect option and joins the server voice channel, but the music isn't playing.

**Comment by Laptopenjoyer** [comment]
Same problem commenting here for whenever you get an answer.

**Comment by codetheweb** [comment]
Was able to reproduce this.

**Comment by codetheweb** [comment]
Fixed in v0.6.1.

**Comment by myde2001** [comment]
Thanks so much.
