### ISSUE TITLE
make a how to build video tutorial

### ISSUE THREAD

**Issue by dragonGRaf** [codetheweb/aoede#40]
im using a linux vps and i cant use ubuntu (error code: -bash: ./ubuntu-latest-aoede: cannot execute binary file: Exec format error) and idk how to build etc
could i get help with it?

**Comment by codetheweb** [comment]
There's instructions on how to build in the readme. I'm not interested in making a video tutorial, but happy to link to one if someone else creates one.

**Comment by dragonGRaf** [comment]
> There's instructions on how to build in the readme. I'm not interested in making a video tutorial, but happy to link to one if someone else creates one.

you mean the [Building from source:](https://github.com/codetheweb/aoede#building-from-source) text? ye not much help since i have no idea how to correctly install all of that and put it together etc
specially not for linux
