### ISSUE TITLE
Compiling error on linux

### ISSUE THREAD

**Issue by dragonGRaf** [codetheweb/aoede#41]
i have a oracle aarch64 linux server 8.8
if you need more info let me know (and how to find them)

`re-3d50aa67b657e808.rlib" "/usr/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcore-5aa4b9f0c6f707f0.rlib" "/usr/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-da53dd03b07bb988.rlib" "-Wl,-Bdynamic" "-lopus" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/usr/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/home/opc/dragon/aoede/aoede-0.6.1/target/release/deps/aoede-9bc28b52b8b6934f" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lopus
          collect2: error: ld returned 1 exit status
          

error: could not compile `aoede` due to previous error`
how to fix or would it be possible to just release a executable file for linux
i cant use ubuntu release (error code: -bash: ./ubuntu-latest-aoede: cannot execute binary file: Exec format error)

**Comment by codetheweb** [comment]
I thought the underlying opus crate was self-contained, but you could try `sudo apt-get install -y libopus-dev`.

**Comment by dragonGRaf** [comment]
> I thought the underlying opus crate was self-contained, but you could try `sudo apt-get install -y libopus-dev`.

my os uses "yum" to install btw
<img width="507" alt="Screenshot 2023-10-27 at 02 32 26" src="https://github.com/codetheweb/aoede/assets/65346683/309be8be-213d-47c8-833e-7288d37069f0">
but ye sadly didnt work

**Comment by codetheweb** [comment]
Looks like the package name for yum might be `opus-devel`.

**Comment by dragonGRaf** [comment]
> Looks like the package name for yum might be `opus-devel`.

alright worked 
thanks finnished building and works
