### ISSUE TITLE
Bot is already on the server, but only prints the invite link on startup

### ISSUE THREAD

**Issue by Bios-Marcel** [codetheweb/aoede#47]
Not much to show honestly.

I am using the docker container, filled out all .env variables and ran it.

It prints:

```
Ready!
Invite me with ....
```

Then there's silence. The bot is on the server and I have joined a voice channel. I also switched once, to make sure that its not a bug where it doesnt work when you start the bot while you are already in a channel.

Is there anything else I can send that would be helpful?

**Comment by Bios-Marcel** [comment]
EDIT: I am dumb ... had to select the device in spotify first.

**Comment by codetheweb** [comment]
This has confused quite a few people, so changing the behavior.

https://github.com/codetheweb/aoede/pull/48
