### ISSUE TITLE
Appear offline when disconnected from VC

### ISSUE THREAD

**Issue by Brramble** [codetheweb/aoede#8]
Hi, 

Just wanted to ask, would you be interested in adding a toggleable feature that when aoede is disconnected from the channel the bot will then appear offline. I think it is definitely preference but with it not being invokable by commands some users ask questions about what the bot does.

**Comment by codetheweb** [comment]
I can set it to show the bot as AFK but I'm not sure if there's a way to show it as disconnected or not.

**Comment by Brramble** [comment]
isn't there an offline option I think it is `invisible` in the library? Just so it appears as invisible when not used and as soon as it is called in it would show online.

**Comment by codetheweb** [comment]
Closed by 6069d48c4f23de817617b36fd029390a4f1f8b6c.

Released in [v0.2.0](https://github.com/codetheweb/aoede/releases/tag/v0.2.0).
